### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ItsAGeekThing**
The links that currently point to the EsperNet Webchat  (Community and Development Chat) have their connections refused when connecting over https. This pull request replaces the https links with the http equivalent.

EDIT: I updated some of the other links to use https in commit 021bc8b

### CODE REVIEW

**Comment by ST-DDT** [comment]
AFAIK they have been taken over ( at least the web chat page.) So maybe we should link the new page directly.

**Comment by JustinHarper** [comment]
@ST-DDT Can you elaborate on what has been taken over? I do not understand.

**Comment by ST-DDT** [comment]
Last time i tried to connect to that page i was forwarded to another page from another provider.
I was worried so i googled and they mentioned that the web (chat) page is unavailable and moved to another site.
I'm not 100% sure whether it was esper or not, but i don't know any other (big) IRC providers.
When i visit the page now everything is back to normal though.

**Comment by JustinHarper** [comment]
@ST-DDT That is weird. Let me see if I can reproduce this.

**Comment by JustinHarper** [comment]
@ST-DDT I can't seem to reproduce what you described, perhaps you could try to connect to the webchat again and see if it still occurs?

**Comment by ST-DDT** [comment]
> EDIT: Perhaps Esper's webchat was down for maintenance and they were temporarily redirecting visitors to Kiwiirc.com to migitate service disruption?

Maybe, but sounds like a good explanation.
(Maybe they tried to fix the https issue?)

> When i visit the page now everything is back to normal though.

Everything works as expected right now.

**Comment by JustinHarper** [comment]
@ST-DDT Alright, good to hear.
I'll go ahead and remove WIP from the title.

**Comment by Zidane** [comment]
Covered in https://github.com/SpongePowered/Sponge/commit/8899a6c377f359f83ee64cc6d8d00bac1201787f

**Pull request closed without merging**
