### PR TITLE
Add SoundEvent Implementation

### PR DESCRIPTION
**Pull request by clienthax**
API: https://github.com/SpongePowered/SpongeAPI/pull/2028

### CODE REVIEW

**Comment by clienthax** [comment]
https://github.com/SpongePowered/SpongeAPI/issues/1562

**Comment by clienthax** [comment]
On a side note, if anyone knows of a SANE way which these magic ids match to any sponge representation, let me know.
1023 = ENTITY_WITHER_SPAWN
1028 = ENTITY_ENDERDRAGON_DEATH
1038 = BLOCK_END_PORTAL_SPAWN
RenderGlobal.broadcastSound

**Comment by simon816** [comment]
Sounds are represented in the API as `SoundType` - https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/effect/sound/SoundTypes.java

**Comment by clienthax** [comment]
@simon816 Those ids arnt soundtypes however by the looks of it they seem to be more "event keys"

**Comment by clienthax** [comment]
Should be ready for review.

**Comment by dualspiral** [comment]
[How will this work with the Forge PlaySoundAtEntityEvent](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/event/entity/PlaySoundAtEntityEvent.java#L52)?

I suspect this event impl is going to need some scaffolding in SpongeForge to either mix in to this event, or having some parings between Forge and Sponge events [such as this](https://github.com/SpongePowered/SpongeForge/blob/a480900d50fbc91a6621b5d25a2b00201a2f715f/src/main/java/org/spongepowered/mod/event/SpongeModEventManager.java#L174). A mod should have the oppotunity to cancel an event at the same time as its Sponge one and see that state, and you may want to change the Forge logic slightly to route to the Sponge event handlers.

A good example of where we do this is the `MessageChannelEvent.Chat` and `ServerChatEvent` pairing - they fire "concurrently" and sync status to each other as the events are sent to each member of their respective handler lists.

**Comment by clienthax** [comment]
@dualspiral Im not too sure on how to link that one in without creating duplicate events currently, will leave it to someone more suited.

**Pull request merged**
