### PR TITLE
Update jansi dep to support ARM64

### PR DESCRIPTION
**Pull request by dualspiral**
See #3429

I haven't got an ARM64 machine up and running to test this (will have to dust off my Raspberry Pi which I _think_ is 64 bit, but I'm hoping someone else will be able to tell me if it works before I get to that tomorrow)

This might not work, or it might not be the best way to do this...

[If someone wants to test this, give this a go - spongevanilla-1.16.5-8.0.0-RC0-universal.jar.zip](https://github.com/SpongePowered/Sponge/files/6658950/spongevanilla-1.16.5-8.0.0-RC0-universal.jar.zip)

### CODE REVIEW

**Comment by dualspiral** [comment]
It turns out I have a 32bit distro on my Pi, simply as I'm using a model 3B. So, I won't be able to test it, but if someone can verify this works for me, then we can pull it. Alternatively, we wait until jline updates its dep and we just do it then.

**Comment by MrSlimeDiamond** [comment]
> See #3429
> 
> I haven't got an ARM64 machine up and running to test this (will have to dust off my Raspberry Pi which I _think_ is 64 bit, but I'm hoping someone else will be able to tell me if it works before I get to that tomorrow)
> 
> This might not work, or it might not be the best way to do this...
> 
> [If someone wants to test this, give this a go - spongevanilla-1.16.5-8.0.0-RC0-universal.jar.zip](https://github.com/SpongePowered/Sponge/files/6658950/spongevanilla-1.16.5-8.0.0-RC0-universal.jar.zip)

The provided link works perfectly fine for me on my ARM machine!

**Comment by MrSlimeDiamond** [comment]
You should probably do this for the api-9 branch too.

**Comment by dualspiral** [comment]
It'll get done when someone next does a merge on it.

**Pull request merged**
