### PR TITLE
Fix SpongeContextCalculator NPE on Client

### PR DESCRIPTION
**Pull request by Faithcaio**
When running Sponge on a Client the InetSocketAddress is unresolved causing a NPE when calculating Permission Contexts.

### CODE REVIEW

**Comment by stephan-gh** [comment]
Note that we cannot expect virtual hosts to resolve correctly. This is something we're usually given by the client, and they can give us anything (even hostnames that don't resolve correctly). Not sure if throwing an exception when it cannot be resolved is a good idea.

**Comment by Faithcaio** [comment]
What should we do then when its invalid?
It currently throws NPEs thats not a good idea either

**Comment by stephan-gh** [comment]
I guess there are two things we can do, not sure which one is better because I don't know much about the permission API:

- Return null if the hostname can't be resolved and modify `buildAddressCache` to skip adding the context entirely if the method returns null (instead of throwing a NPE).
- Given that the virtual host should usually point to the server itself, we could use the local IP address of the server as a fallback.

**Comment by Zidane** [comment]
@lucko 

Thoughts on the above?

**Comment by lucko** [comment]
As long as the caches account for a null value, then that's fine.

The current fix looks good imo.

**Comment by Zidane** [comment]
@Faithcaio 

Does it?

**Comment by lucko** [comment]
Yes, null is handled inside of the load method :+1:

**Pull request merged**
