### PR TITLE
Refactor Common Issue Template

### PR DESCRIPTION
**Pull request by phit**
Same as for Forge but for Common, not sure if we should add a section for code snippets?

### CODE REVIEW

**Comment by ryantheleach** [comment]
```
<!-- 
Plugin Authors: 
  Please attach in a gist, a [Short, Self Contained, Compilable, Example](http://sscce.org/) Plugin that demonstrates the strange behavior. If you are unable to replicate it with a test plugin, how do you expect the Sponge devs to be able to?

  For examples, please see : https://github.com/SpongePowered/SpongeCommon/tree/bleeding/testplugins/src/main/java/org/spongepowered/test
-->
```

**Comment by phit** [comment]
markdown doesn't do anything in issue templates, so the link part to sscce.org is useless as you can't click it
>If you are unable to replicate it with a test plugin, how do you expect the Sponge devs to be able to?

sounds really condescending, no reason to be hostile

I figured something like this replacing the last comment would work
```
<!-- If you are a developer, please attach a short and self contained code snippet to replicate your issue.
        Any relevant log files and snippets should be uploaded to gist.github.com!
        Don't use hastebin/pastebin or other similar sites, as they have a history of quickly
        deleting files before we can look at them. -->
```

**Comment by ryantheleach** [comment]
I would still appreciate the link to sscce , it summarizes a lot of the points that would otherwise be too long.

**Comment by ryantheleach** [comment]
LGTM

**Comment by ST-DDT** [comment]
I dont seem to be able to connect to http://sscce.org properly. I get certificate warnings and 401.

**Comment by phit** [comment]
stop whatever is redirecting the page to https in your browser, its certificate points to a different domain

**Pull request merged**
