### PR TITLE
Update Database Dependencies

### PR DESCRIPTION
**Pull request by vectrixdevelops**
After encountering some issues with the current database versions, as well as lacking certain things possible in newer versions, I think they would suite a good ol' update.

### CODE REVIEW

**Comment by kashike** [comment]
Does this break compatibility at all?

**Comment by parlough** [comment]
From my look over the changelogs and commits, the changes seem to be mostly bugfixes, better Java 8 compatibility, and other small improvements. No major breaking changes. Best to keep these changes to API 7 just in-case though.

**Comment by vectrixdevelops** [comment]
It should not as far as I have tested and looked through the commits and news of each dependency.

**Comment by stephan-gh** [comment]
Thanks for the PR! There were some new updates since you submitted the PR so I used the chance and updated them again in https://github.com/SpongePowered/SpongeCommon/commit/f1a78588a72517d2803648757fd29d1a3afd9747

**Pull request closed without merging**
