### PR TITLE
Remove requirement for events to extend AbstractEvent

### PR DESCRIPTION
**Pull request by simon816**
Can also go into `stable-5`

### CODE REVIEW

**Review by kashike — APPROVED** [review]

**Comment by liach** [comment]
Does this hurt existing behavior?

**Comment by ST-DDT** [comment]
What are the implications of not extending AbstractEvent? Why was that needed in the first place?

**Comment by kashike** [comment]
Requiring extension of `AbstractEvent` was only introduced when https://github.com/SpongePowered/SpongeCommon/commit/4d8439796cdd4b76569a97286ef2e04cf07976c3 was pushed, and only because events are not checked for `instanceof AbstractEvent` before casted.

**Review by stephan-gh — APPROVED** [review]

**Comment by kashike** [comment]
related: https://github.com/SpongePowered/SpongeCommon/commit/bc8c8840c6a0ffc25688c4a61221c9a78359d327

**Comment by liach** [comment]
Congratulations for that commit, thanks kashike!

**Pull request merged**
