### PR TITLE
Fixed RCON and call the events/commands on the main thread.

### PR DESCRIPTION
**Pull request by Cybermaxke**
Also calls the `RconConnectionEvent.Connect` event, which wasn't done before.

Can be test with: https://bukkit.org/threads/admin-rcon-mcrcon-remote-connection-client-for-minecraft-servers.70910/

### CODE REVIEW

**Review by parlough — APPROVED** [review]

**Comment by kashike** [comment]
Is this ready, @Cybermaxke?

**Comment by Cybermaxke** [comment]
@kashike It's ready

**Comment by vorpalhex** [comment]
This fixes #1862 which is also affecting me. Would love to see this finish getting merged in.

**Comment by kashike** [comment]
Thanks, @Cybermaxke.

**Pull request merged**
