### PR TITLE
Add tests for CatalogType methods

### PR DESCRIPTION
**Pull request by ST-DDT**
Added a test that checks whether CatalogType methods are properly implemented.

I tried fixing the broken methods as far as possible and set the remaining to ignored to avoid failing builds for the other developers. The main purpose is to uncover existing failures and prevent future implementation issues.
I won't fix the remaining (ignored) failures as this would probably explode this PR. 
(Except for simple fixes)

Based on https://github.com/SpongePowered/SpongeCommon/issues/739#issuecomment-290988331

### CODE REVIEW

**Comment by stephan-gh** [comment]
@ST-DDT What's wrong with all the `getTranslation()` methods? Are these catalog types that simply don't have any translation we could return or do they return the wrong translations?

**Comment by ST-DDT** [comment]
Most of those methods are not implemented and thus throw an AbstractMethodError. See last commit for all AME candidates.

**Comment by stephan-gh** [comment]
@ST-DDT As far as I can see you already had the implementation for most of these in #387. It would be nice if you could open a new PR with the implemented `getTranslation()` methods.

**Comment by ST-DDT** [comment]
I'll start with only those "not yet implemented" `getTranslation()` methods.

**Comment by ST-DDT** [comment]
I implemented the missing methods in #1306 if that PR is merged then this unit test will become green. (and all AbstractMethodErrors can be removed from the ignore list)

**Comment by ST-DDT** [comment]
Updated to latest bleeding. Tests still works as expected.

**Comment by ST-DDT** [comment]
Updated to latest bleeding. Tests still works as expected. They will get green when #1306 is merged. Someone willing to merge this in?

**Pull request closed without merging**
