### PR TITLE
Migrate several patches to SV since they're now in Forge proper.

### LINKED ISSUE #3003: Just Installed SpongeForge and server wont start
I am currently running the newest 1.12.2 version of sponge forge through my hosted server company. And when I installed I recieved this crash. Heres the log:

[sponge crash.txt](https://github.com/SpongePowered/SpongeForge/files/3722190/sponge.crash.txt)

### PR DESCRIPTION
**Pull request by JBYoshi**
**SpongeCommon** | [SpongeVanilla](https://github.com/SpongePowered/SpongeVanilla/pull/421)

All these patches were added to Forge just over a year ago in MinecraftForge/MinecraftForge#5160, so they no longer need to be applied to Forge.

Note that the configuration options are still available on Forge. Not sure whether they should be marked as SpongeVanilla-only.

Fixes https://github.com/SpongePowered/SpongeForge/issues/3003.

### CODE REVIEW

**Comment by ImMorpheus** [comment]
`NetHandlerPlayServerMixin_LimitBookSize` is also useless. It was added by https://github.com/SpongePowered/SpongeCommon/commit/0f8df35e74e1e1cce7974220e8c5e1df68acd9fa to fix https://github.com/SpongePowered/SpongeCommon/issues/2156.

Forge fixed the core issue. (see https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/world/chunk/storage/RegionFile.java.patch)

**Comment by largeorbitalobject** [comment]
How do we migrate these patches into our Sponge?

**Comment by JBYoshi** [comment]
@ImMorpheus Moved that patch and rebased on latest.

**Comment by dualspiral** [comment]
> Not sure whether they should be marked as SpongeVanilla-only.

If you could just update the configuration comments to state that they only affect SpongeVanilla, then that should suffice for now, I would think. There is a wider question about config along with SF/SV specific options, but that's not really for solving here.

Otherwise, this is a straight move of code from SC to SV. Quick look suggests no issues - but I imagine you've throughly tested it!

**Pull request merged**
