### PR TITLE
Unify Forge and Vanilla implementation v3

### PR DESCRIPTION
**Pull request by Minecrell**
See #232 for more information.

This is pretty much complete, and moves most code into the Common module which is currently still in the [`common2`](https://github.com/SpongePowered/Sponge/tree/common2) branch, but is going to be in a dedicated repository when merged.

A lot of mixins are currently Forge-only because they depend on Forge in one or another way, we can probably go through them later and separate some shared things into additional mixins.

#### TODO
- [x] Update to latest master
- [x] Fix a few Gradle bugs (wrong project name, Sponge version)

@SpongePowered/developers Looking for feedback on this so we can get this merged in the next few days.

### CODE REVIEW

**Comment by Minecrell** [comment]
@SpongePowered/developers This is ready for merge now. I've pushed to Common code to SpongePowered/SpongeCommon. Can we get this merged in the next 2 days?

**Comment by halvors** [comment]
Why is this closed? Isn't it going to be merged?

**Comment by zml2008** [comment]
it just was -- look at the commit this was closed from.

**Comment by halvors** [comment]
Ah i see.

**Pull request closed without merging**
