### PR TITLE
Fix PotionEffect retrieval error from DataContainer

### PR DESCRIPTION
**Pull request by ImMorpheus**
Fix https://github.com/SpongePowered/SpongeCommon/issues/1276

~qa

### CODE REVIEW

**Comment by XakepSDK** [comment]
@gabizou you should do something with this. This is second time i seen that type of errors.

**Comment by gabizou** [comment]
> @gabizou you should do something with this. This is second time i seen that type of errors.

I'll give you another chance at rephrasing that statement.

**Comment by ImMorpheus** [comment]
~qa

**Review by parlough — APPROVED** [review]

**Review by kashike — APPROVED** [review]

**Review by gabizou — APPROVED** [review]

**Comment by Aaron1011** [comment]
Merged in https://github.com/SpongePowered/SpongeCommon/commit/b834524772a032b68c919be18e6f8b04ea8bc63e.

**Pull request closed without merging**
