### PR TITLE
Fix worldarchetype builder spawnloaded npe

### PR DESCRIPTION
**Pull request by liach**
per zidane's request on irc.

### CODE REVIEW

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/008e5d5274ba435f5baac3e6b21b45b4be472203#diff-88d512170c6d39b0117572b34a5fddb2L226

this was changed for a reason, all dims besides overworld should default to false

**Comment by liach** [comment]
should i change it to false then?

**Comment by liach** [comment]
however, this change simply crashes plugins now.

**Comment by Zidane** [comment]
I think setting it to false should be fine unless I am forgetting something that @phit  remembers.

**Comment by phit** [comment]
setting it to false will also set it to false for the overworld, don't think that will not crash

why is this PR needed anyways?

**Comment by Zidane** [comment]
@phit 

Well Overworld would be ignored of course. Its ignored in other areas already :p.

**Comment by phit** [comment]
if what you are saying is correct, @bloodmc why was this special handling in your commit even necessary?

**Comment by liach** [comment]
Ah then my fix is wrong. I will make a better fix then.

**Comment by liach** [comment]
@phit I have corrected that fix now.

**Comment by liach** [comment]
hmm git derped

**Comment by liach** [comment]
This time it should be good @phit

**Comment by liach** [comment]
Thanks blood!

**Comment by liach** [comment]
@kashike Can you cherry pick this to bleeding?

**Pull request merged**
