### PR TITLE
Refactoring and implementation of the LaunchProjectileEvent

### PR DESCRIPTION
**Pull request by RedNesto**
[SpongeAPI](https://github.com/SpongePowered/SpongeAPI/pull/1766) | **SpongeCommon**

This PR implement its SpongeAPI counterpart.

### When is the event fired ?

Here are each cases I tested:
- [x] A non-player entity shoots a projectile (skeletons shooting arrows, llamas spitting, ghasts shooting fireballs, snowmans shooting snowballs, blaze shooting small fireballs)
- [x] A player shoots arrows (with a bow heh)
- [x] A player throws projectiles (snowballs, eggs, potions - splash and lingering -, enderpearls, eyes of ender, using fishing rod, experience bottle)
- [x] A dispenser dispenses projectiles (arrows, snowballs, eggs, potions - splash and lingering -, experience bottle)
- [x] A plugin shoots a projectile
- [x] A player uses a firework.
- [x] A dispenser dispenses a firework.
- [x] A Wither attacks.
- [x] The dragon shoots a fireball

Tell me if you see a case of projectile I missed.

[And there is the content of a test plugin](https://gist.github.com/RedNesto/a1c45a36bf79e190dae512ee867daeac)

~Note: It seems that there are two projectile-related `EventContextKeys`, `PROJECTILE_SOURCE` and `THROWER`, from what I saw, only one would be necessary, I may address this issue later if it is considered as one.~
Fixed in 5d0184de3b1eeba951c5873d9c20c919c7a8d307

### CODE REVIEW

**Comment by ryantheleach** [comment]
~qa

**Comment by kashike** [comment]
~qa

**Comment by RedNesto** [comment]
~wip

**Comment by gabizou** [comment]
This will need to be re-done and re-target `api-8`. Bleeding is no longer a valid branch.

**Pull request closed without merging**
