### PR TITLE
Nicer build errors

### PR DESCRIPTION
**Pull request by gratimax**
Adds some nicer error logging and forced errors for people who miss common steps.

See #182, #171, #154, #178, #79, (and many others...) for examples.

Some things still to be done:
- [ ] Hooking into gradle finding dependencies to catch the infamous '403 Forbidden' error for people who have not run `gradle setupDecompWorkspace --refresh-dependencies`
- [x] Adding submodule detection to the gradlew scripts (since they refer to the submodules)
- [x] Make @kenzierocks happy by turning this into a todo list

### CODE REVIEW

**Comment by danshadeck** [comment]
Thanks for this!

**Comment by simon816** [comment]
How about automatically running `git submodule update --init --recursive` instead of outputting that to the user? The less steps the better.

**Comment by kenzierocks** [comment]
Why not both! I'm rewriting those scripts now.

**Comment by kenzierocks** [comment]
https://github.com/kenzierocks/Sponge/commit/e7a889e9e38f2411ca34fe885901365798b68f9b

**Comment by kenzierocks** [comment]
Merge https://github.com/kenzierocks/Sponge/tree/feature/nice-build-errors for applying @simon816's suggestions.

**Comment by AbrarSyed** [comment]
*stamps approval*

**Comment by kenzierocks** [comment]
@AbrarSyed that top point is yours to do.

**Comment by bloodmc** [comment]
@gratimax What's the status of this PR?

**Comment by gratimax** [comment]
Waiting on @AbrarSyed to get into the first one, if he has time. It'd be rather hard to fix the '403 Forbidden' error, but it's the most compelling one to do.

**Comment by AbrarSyed** [comment]
Don't hold your breath on the 403 issue. If there is a fix, I'm gonna make it globally in FG...

**Pull request closed without merging**
