### PR TITLE
Make MixinItemMap methods respect client side more

### PR DESCRIPTION
**Pull request by liach**
Resolves SpongePowered/SpongeForge#1996

Also make up some missing redirects that should happen

Signed-off-by: liach <liach@users.noreply.github.com>

### CODE REVIEW

**Comment by liach** [comment]
My first commit failed because of static issues. This time it should be fine.

**Comment by liach** [comment]
Four screenshots proving that my patch works :smiley:

**Comment by liach** [comment]
@XakepSDK This pull fixes your map crash, too.

**Comment by phit** [comment]
~qa

**Comment by liach** [comment]
thanks!

**Comment by liach** [comment]
you may cherry pick this commit onto bleeding, too.

**Pull request merged**
