### PR TITLE
Cache the particle effects packet data and fixed some issues.

### PR DESCRIPTION
**Pull request by Cybermaxke**
Fixes SpongePowered/SpongeVanilla#275
Fixes SpongePowered/SpongeCommon#1009

### CODE REVIEW

**Comment by stephan-gh** [comment]
Is there a reason why you don't "cache" the packet data directly as a field on `SpongeParticleEffect`? If you have a cache with weak keys on a class we control then it sounds like that could be also just a field that is lazily initialized.

**Comment by Maxqia** [comment]
Plz Merge

**Comment by stephan-gh** [comment]
@Cybermaxke 
Please update this for the 1.11 update we merged yesterday.

**Comment by gabizou** [comment]
Or, potentially rebase onto `stable-5` and re-assign the PR to it as well.

**Comment by Cybermaxke** [comment]
@Minecrell, done.

**Review by stephan-gh — APPROVED** [review]

**Pull request merged**
