### PR TITLE
Add an optimized version of Entity.getNearbyEntities(double).

### PR DESCRIPTION
**Pull request by JBYoshi**
The `default`-implemented version in the API checks every entity in the world. This version only checks entities in chunks that could be within the specified distance.

### CODE REVIEW

**Comment by NeumimTo** [comment]
It would be actually helpful to also add a method World#getNearbyEntities(Position, radius), a method, where we wont need to use an entity as the centre. 
This could be extended maybe to World#getNearbyEntities(Position, radius, loadchunks) ...

**Comment by Zidane** [comment]
@NeumimTo 

Open issue on API then. Not the focus of this PR.

**Comment by Zidane** [comment]
@JBYoshi 

The default implemented version in the API, frankly, sucks and any implementation (SpongeCommon, Lantern) will surely override it. Can you do an API PR and further this PR to correct that?

@Meronat You'll need to update Lantern for that.

**Comment by JBYoshi** [comment]
Superseded by SpongePowered/SpongeAPI#1630.

**Pull request closed without merging**
