### PR TITLE
Add some helper methods for working with ServerBossBars

### PR DESCRIPTION
**Pull request by kashike**
[API](https://github.com/SpongePowered/SpongeAPI/pull/1534) | [**Common**](https://github.com/SpongePowered/SpongeCommon/pull/1296)

### CODE REVIEW

**Review by ST-DDT — APPROVED** [review]

**Comment by Zidane** [comment]
@kashike 

Need another update on this. Also is this WIP?

**Comment by ryantheleach** [comment]
Talked to kashike, Current status is a slight rework in the relationship between players and bossbars vs their helper methods. I don't know exact details, but have heard there will be work on this soon.

**Comment by ImMorpheus** [comment]
@kashike Is this ready ? (I can test it if you fix the conflicts)

**Comment by ImMorpheus** [comment]
I've fixed the conflicts. IMO this would be a good addition to stable-7

**Pull request merged**
