### PR TITLE
Add Parallel GZIP Optimization.

### PR DESCRIPTION
**Pull request by clienthax**

### CODE REVIEW

**Comment by clienthax** [comment]
Will likely change this to use https://engineering.linkedin.com/blog/2019/02/migz-for-compression-and-decompression

**Comment by phit** [comment]
is this an actual issue? even the biggest data the game has is not above 8mb files usually, looking at those benchmarks from linkedin and the perf improvements on GB large files, this would give micro seconds improvements at best. depending on the initial overhead it may not be an improvement at all, do you have any data to support that this helps?

**Comment by clienthax** [comment]
@phit none currently, it seems it could help during large pregens and retrogen operations but I need to test it properly

**Comment by clienthax** [comment]
Closing this until i can do tests

**Pull request closed without merging**
