### PR TITLE
Lower the priority of tracker related mixins with overwrites.

### PR DESCRIPTION
**Pull request by gabizou**
Attempt at fixing #3657

### CODE REVIEW

**Comment by Zidane** [comment]
@gabizou 

We could just lower the priority of all the tracker mixins (I'd prefer to not have these separations). Most of the overwrite code is with the tracker afterall.

**Comment by dualspiral** [comment]
Rebased onto latest api-8 code for testing purposes. If we can lower all mixin priority then we should, though this is priority 1102 and the core is 1101 - does that mean we should lower the core priority too?

**Comment by gabizou** [comment]
I think we'll have to evaluate a lot of our mixins lowering priority than default. Some things are "Wanted" at higher priority (like redirects/injections) while other things that are overwrites should be lower priority than the evaluator for redirects etc. At least, that's my view on it.

**Comment by dualspiral** [comment]
> Some things are "Wanted" at higher priority (like redirects/injections) while other things that are overwrites should be lower priority than the evaluator for redirects etc. At least, that's my view on it.

This is pretty much the conclusion I've come to, namely:

* Overwrites need to be at lower priorities, as mod mixins might inject into them at default.
* Injections etc. should be at higher priorities, such that we can inject into (well crafted) mod overwrites.

I'd imagine that this will solve some as of yet unknown incompatibilities with mods that use mixins - most mods probably won't use the idea of mixin priorities.

**Comment by Enterprise12nx01** [comment]
ive tried the latest spongeforge spongeforge-1.16.5-36.2.5-8.1.0-RC1152
has the issue been fixed yet or in an older version?

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please rebase this PR on the current branch and reopen it.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1

**Pull request closed without merging**
