### PR TITLE
Fix no event being thrown when lava spreads fire

### PR DESCRIPTION
**Pull request by ImMorpheus**
Fix https://github.com/SpongePowered/SpongeCommon/issues/1446

### CODE REVIEW

**Comment by Zidane** [comment]
@ImMorpheus 

Want to finally make ChangeBlockEvent.Grow work :D?

**Comment by Faithcaio** [comment]
Why not remove it instead? And make it a Context
(Decay too)

**Comment by Zidane** [comment]
@Faithcaio 

We can do that, yes but that is an API break.

**Comment by RedNesto** [comment]
I'm actually working on the removal of ChangeBlockEvent.Grow and Decay for API 8, by putting them into the context of ChangeBlockEvent.

**Pull request closed without merging**
