### PR TITLE
Throw an exception when using Entity#remove on a player. Close #989

### LINKED ISSUE #989: Entity removal of Player doesn't kick
Currently when a Player is removed (`Entity#remove()`), they just exist in some kind of weird state where they can't interact with anything, and updates are no longer sent to them (outside of the time).

My suggestion is that `Player` override `remove()` and re-direct it to whatever handles kicking a player.

/shrug

https://forums.spongepowered.org/t/entity-removal-help/15336

### PR DESCRIPTION
**Pull request by ImMorpheus**
Let me know if I need to add a test plugin or a message when throwing the exception.

### CODE REVIEW

**Comment by Zidane** [comment]
@ImMorpheus 

Can you change your target to stable-7?

**Comment by parlough** [comment]
Maybe add a short message to the exception explaining why?

**Comment by Zidane** [comment]
@ImMorpheus @Meronat 

This needs to be on stable-7...Player entities in the MCP implementation should never be told to just remove...it causes all hell to break loose and I don't need a plugin dev blindly calling that without thinking about it first.

**Comment by parlough** [comment]
@Zidane It caused problems with his PR(quick fix but still), it needs to be in bleeding too anyway, and we can easily cherry pick the change. it's going to be a pain to keep asking people to switch to stable-7 as they have different bases and the default is bleeding at the moment. Dual made a good point we should target bleeding as it is bleeding and cherry-pick to 7 not the other way around just like we normally do.

**Review by parlough — APPROVED** [review]

**Comment by Zidane** [comment]
@Meronat 

Generally I agree but with something so minor I don't want lagtime on fixes to stable-7.

**Pull request merged**
