### PR TITLE
Check if root container has any viewed inventories before accessing.

### PR DESCRIPTION
**Pull request by hsyyid**
Refer to https://github.com/SpongePowered/SpongeCommon/issues/2045

Simply added a `hasNext` check before trying to call `next`

### CODE REVIEW

**Comment by ryantheleach** [comment]
~qa

**Comment by Faithcaio** [comment]
Solved it by just getting the first inventory with `fabric.get(0)`
The error only happened with modded inventories anyways and we are only checking for custom inventories here.

**Comment by hsyyid** [comment]
@Faithcaio your fix did not resolve the issue,  new stacktrace:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_121]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_121]
	at net.minecraft.inventory.Container.func_75139_a(Container.java:120) ~[afr.class:?]
	at org.spongepowered.common.item.inventory.lens.impl.fabric.ContainerFabric.get(ContainerFabric.java:74) ~[ContainerFabric.class:1.12.2-2705-7.1.0-BETA-3406]
	at org.spongepowered.common.item.inventory.lens.impl.fabric.ContainerFabric.get(ContainerFabric.java:42) ~[ContainerFabric.class:1.12.2-2705-7.1.0-BETA-3406]
	at org.spongepowered.common.item.inventory.adapter.impl.AdapterLogic.inventoryRoot(AdapterLogic.java:303) ~[AdapterLogic.class:1.12.2-2705-7.1.0-BETA-3406]
	at org.spongepowered.common.item.inventory.adapter.impl.AdapterLogic.getRootProperty(AdapterLogic.java:277) ~[AdapterLogic.class:1.12.2-2705-7.1.0-BETA-3406]
	at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.getProperty(MinecraftInventoryAdapter.java:174) ~[MinecraftInventoryAdapter.class:1.12.2-2705-7.1.0-BETA-3406]
	at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.getInventoryProperty(MinecraftInventoryAdapter.java:188) ~[MinecraftInventoryAdapter.class:1.12.2-2705-7.1.0-BETA-3406]
```

**Comment by Faithcaio** [comment]
ffs how are there empty containers it makes no sense. I'll look at it later.

**Pull request closed without merging**
